name: Download bestcfv4.txt

on:
  # 触发条件：手动触发或定时任务
  workflow_dispatch: # 支持手动触发
  schedule:
    - cron: "0 */6 * * *" # 每6小时运行一次（可调整）

jobs:
  download-file:
    env:
      GITHUB_TOKEN: ${{ secrets.GT_TOKEN }}
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 第二步：创建目录并下载文件
      - name: Create Directory and Download File
        run: |
          # 定义目标路径
          TARGET_DIR="BestCF"
          TARGET_FILE="$TARGET_DIR/bestcfv4.txt"

          # 创建目标目录（如果不存在）
          if [ ! -d "$TARGET_DIR" ]; then
            mkdir -p "$TARGET_DIR"
            echo "✅ 目录 $TARGET_DIR 已创建"
          else
            echo "ℹ️ 目录 $TARGET_DIR 已存在"
          fi

          # 下载文件
          curl -L https://raw.githubusercontent.com/ymyuuu/IPDB/main/BestCF/bestcfv4.txt -o "$TARGET_FILE"
          if [ $? -eq 0 ]; then
            echo "✅ 文件已成功下载到 $TARGET_FILE"
          else
            echo "❌ 文件下载失败，请检查网络连接或URL是否有效"
            exit 1
          fi

      # 第三步：提交更改（如果有）
      - name: Commit Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .

          # 检查是否有更改
          if git diff-index --quiet HEAD; then
            echo "ℹ️ 文件未更新，无需提交"
          else
            git commit -m ":arrow_up: Update bestcfv4.txt"
            echo "✅ 文件已更新并提交"
            git push
          fi

      # 第四步：推送更改到远程仓库
      #- name: Push Changes
      #  run: |
      #    # 推送更改到远程仓库
      #    if git diff-index --quiet HEAD; then
      #      echo "ℹ️ 没有更改需要推送"
      #    else
      #      git push origin ${{ github.ref }}
      #      if [ $? -eq 0 ]; then
      #        echo "✅ 更改已成功推送到远程仓库"
      #      else
      #        echo "❌ 推送失败，请检查权限或网络连接"
      #        exit 1
      #      fi
      #    fi
