name: Update Cloudflare KV

on:
  push:
    branches:
      - main # 触发分支
  workflow_dispatch: # 手动触发选项

jobs:
  update-kv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Load Environment Variables
        run: echo "加载环境变量..."
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_NAMESPACE_ID: ${{ secrets.CF_NAMESPACE_ID }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_AUTH_EMAIL: ${{ secrets.CF_AUTH_EMAIL }}
          IP_FILE_PATH: ./BestCF/bestcfv4.txt # 替换为实际文件路径

      - name: Run Script to Update KV
        run: |
          python .github/workflows/put_cloudflare.py
