name: Update Cloudflare KV

on:
  # 手动触发
  workflow_dispatch:

  # 推送触发（仅限 main 分支且 BestCF/bestcfv4.txt 文件更新时）
  push:
    branches:
      - main
    paths:
      - "BestCF/bestcfv4.txt" # 仅在该文件更新时触发

  # 定时任务（每天凌晨 2 点执行，无论文件是否更新）
  schedule:
    - cron: "0 2 * * *"

jobs:
  update-kv:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r .github/workflows/requirements.txt

      # Step 4: Update Cloudflare KV
      - name: Update Cloudflare KV
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CF_NAMESPACE_ID: ${{ secrets.CF_NAMESPACE_ID }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          CF_AUTH_EMAIL: ${{ secrets.CF_AUTH_EMAIL }}
          CF_KEY_NAME: ${{ secrets.CF_KEY_NAME }}
        run: |
          echo "开始更新 Cloudflare KV..."
          python .github/workflows/put_cloudflare.py
