name: Daily IP Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"  # 北京时间6:00 (UTC+8)

jobs:
  scrape-ips:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整提交历史

    - name: Extract and merge IPs
      run: |
        # 获取旧IP列表
        if [ -f ip.txt ]; then
          cp ip.txt old_ip.txt
        else
          touch old_ip.txt
        fi

        # 提取新IP
        curl -s https://www.wetest.vip/page/cloudflare/total_v4.html | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" > ip1.txt
        curl -s https://raw.githubusercontent.com/ymyuuu/IPDB/main/BestCF/bestcfv4.txt | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" > ip2.txt
        cat ip1.txt ip2.txt | sort -u > new_ip.txt

        # 比较差异
        if cmp -s old_ip.txt new_ip.txt; then
          echo "IP列表无变化，跳过提交"
          echo "SKIP_COMMIT=true" >> $GITHUB_ENV
        else
          echo "发现新IP，准备提交"
          mv new_ip.txt ip.txt
          echo "SKIP_COMMIT=false" >> $GITHUB_ENV
        fi

        # 显示统计信息
        echo "旧IP数量: $(wc -l < old_ip.txt)"
        echo "新IP数量: $(wc -l < ip.txt)"
        
    - name: Cleanup
      run: rm -f ip1.txt ip2.txt old_ip.txt new_ip.txt

    - name: Commit changes
      if: env.SKIP_COMMIT == 'false'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ip.txt
        git commit -m "IP更新 [$(date +'%Y-%m-%d %H:%M')]"
        git push https://x-access-token:${{ secrets.GT_TOKEN }}@github.com/${{ github.repository }}.git

