name: Scrape IP Addresses

on:
  schedule:
    - cron: "0 * * * *"  # 每小时执行一次

jobs:
  scrape-ip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false  # 重要：必须关闭凭据持久化

    - name: Extract IP addresses
      run: |
        curl -s https://www.wetest.vip/page/cloudflare/total_v4.html | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" > ip.txt

    - name: Commit and Push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ip.txt
        git commit -m "Update IP addresses"
        git push https://x-access-token:${{ secrets.GT_TOKEN }}@github.com/${{ github.repository }}.git
